program Compiler;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  System.SysUtils,
  JsonFlow.Arrays in '..\Source\JSON\Composition\JsonFlow.Arrays.pas',
  JsonFlow.Composer in '..\Source\JSON\Composition\JsonFlow.Composer.pas',
  JsonFlow.Objects in '..\Source\JSON\Composition\JsonFlow.Objects.pas',
  JsonFlow.Pair in '..\Source\JSON\Composition\JsonFlow.Pair.pas',
  JsonFlow.Converters in '..\Source\JSON\Core\JsonFlow.Converters.pas',
  JsonFlow.Interfaces in '..\Source\JSON\Core\JsonFlow.Interfaces.pas',
  JsonFlow.Utils in '..\Source\JSON\Core\JsonFlow.Utils.pas',
  JsonFlow.Value in '..\Source\JSON\Core\JsonFlow.Value.pas',
  JsonFlow.Converter.Dataset in '..\Source\JSON\IO\JsonFlow.Converter.Dataset.pas',
  JsonFlow.Navigator in '..\Source\JSON\IO\JsonFlow.Navigator.pas',
  JsonFlow.Reader in '..\Source\JSON\IO\JsonFlow.Reader.pas',
  JsonFlow.Serializer.Attributes in '..\Source\JSON\IO\JsonFlow.Serializer.Attributes.pas',
  JsonFlow.Serializer.CircularRef in '..\Source\JSON\IO\JsonFlow.Serializer.CircularRef.pas',
  JsonFlow.Serializer in '..\Source\JSON\IO\JsonFlow.Serializer.pas',
  JsonFlow.Serializer.Pool in '..\Source\JSON\IO\JsonFlow.Serializer.Pool.pas',
  JsonFlow.Writer in '..\Source\JSON\IO\JsonFlow.Writer.pas',
  JsonFlow.MiddlewareDatatime in '..\Source\JSON\Middleware\JsonFlow.MiddlewareDatatime.pas',
  JsonFlow in '..\Source\JsonFlow.pas',
  JsonFlow.SchemaComposer in '..\Source\Schema\Composition\JsonFlow.SchemaComposer.pas',
  JsonFlow.SchemaNavigator in '..\Source\Schema\Composition\JsonFlow.SchemaNavigator.pas',
  JsonFlow.AsyncValidator in '..\Source\Schema\Core\JsonFlow.AsyncValidator.pas',
  JsonFlow.ErrorListPool in '..\Source\Schema\Core\JsonFlow.ErrorListPool.pas',
  JsonFlow.Metrics in '..\Source\Schema\Core\JsonFlow.Metrics.pas',
  JsonFlow.PersistentCache in '..\Source\Schema\Core\JsonFlow.PersistentCache.pas',
  JsonFlow.Reports in '..\Source\Schema\Core\JsonFlow.Reports.pas',
  JsonFlow.Schema in '..\Source\Schema\Core\JsonFlow.Schema.pas',
  JsonFlow.ValidationEngine in '..\Source\Schema\Core\JsonFlow.ValidationEngine.pas',
  JsonFlow.ValidationRules in '..\Source\Schema\Core\JsonFlow.ValidationRules.pas',
  JsonFlow.SchemaReader in '..\Source\Schema\IO\JsonFlow.SchemaReader.pas',
  JsonFlow.SchemaRefIndy in '..\Source\Schema\IO\JsonFlow.SchemaRefIndy.pas',
  JsonFlow.FormatValidators.Brazil in '..\Source\Schema\Validators\Format\Brazil\JsonFlow.FormatValidators.Brazil.pas',
  JsonFlow.FormatValidators.BrazilianLicensePlate in '..\Source\Schema\Validators\Format\Brazil\JsonFlow.FormatValidators.BrazilianLicensePlate.pas',
  JsonFlow.FormatValidators.BrazilianPhone in '..\Source\Schema\Validators\Format\Brazil\JsonFlow.FormatValidators.BrazilianPhone.pas',
  JsonFlow.FormatValidators.CEP in '..\Source\Schema\Validators\Format\Brazil\JsonFlow.FormatValidators.CEP.pas',
  JsonFlow.FormatValidators.CNPJ in '..\Source\Schema\Validators\Format\Brazil\JsonFlow.FormatValidators.CNPJ.pas',
  JsonFlow.FormatValidators.CPF in '..\Source\Schema\Validators\Format\Brazil\JsonFlow.FormatValidators.CPF.pas',
  JsonFlow.FormatValidators.Base in '..\Source\Schema\Validators\Format\JsonFlow.FormatValidators.Base.pas',
  JsonFlow.FormatValidators.Date in '..\Source\Schema\Validators\Format\JsonFlow.FormatValidators.Date.pas',
  JsonFlow.FormatValidators.DateTime in '..\Source\Schema\Validators\Format\JsonFlow.FormatValidators.DateTime.pas',
  JsonFlow.FormatValidators.Email in '..\Source\Schema\Validators\Format\JsonFlow.FormatValidators.Email.pas',
  JsonFlow.FormatValidators.Ipv4 in '..\Source\Schema\Validators\Format\JsonFlow.FormatValidators.Ipv4.pas',
  JsonFlow.FormatValidators.Ipv6 in '..\Source\Schema\Validators\Format\JsonFlow.FormatValidators.Ipv6.pas',
  JsonFlow.FormatValidators.Time in '..\Source\Schema\Validators\Format\JsonFlow.FormatValidators.Time.pas',
  JsonFlow.FormatValidators.Uri in '..\Source\Schema\Validators\Format\JsonFlow.FormatValidators.Uri.pas',
  JsonFlow.FormatValidators.Uuid in '..\Source\Schema\Validators\Format\JsonFlow.FormatValidators.Uuid.pas',
  JsonFlow.FormatRegistry in '..\Source\Schema\Validators\JsonFlow.FormatRegistry.pas',
  JsonFlow.FormatValidators in '..\Source\Schema\Validators\JsonFlow.FormatValidators.pas',
  JsonFlow.SchemaValidator in '..\Source\Schema\Validators\JsonFlow.SchemaValidator.pas',
  JsonFlow.ValidationRules.AdditionalProperties in '..\Source\Schema\Validators\JsonFlow.ValidationRules.AdditionalProperties.pas',
  JsonFlow.ValidationRules.AllOf in '..\Source\Schema\Validators\JsonFlow.ValidationRules.AllOf.pas',
  JsonFlow.ValidationRules.AnyOf in '..\Source\Schema\Validators\JsonFlow.ValidationRules.AnyOf.pas',
  JsonFlow.ValidationRules.Base in '..\Source\Schema\Validators\JsonFlow.ValidationRules.Base.pas',
  JsonFlow.ValidationRules.Conditional in '..\Source\Schema\Validators\JsonFlow.ValidationRules.Conditional.pas',
  JsonFlow.ValidationRules.Consts in '..\Source\Schema\Validators\JsonFlow.ValidationRules.Consts.pas',
  JsonFlow.ValidationRules.Contains in '..\Source\Schema\Validators\JsonFlow.ValidationRules.Contains.pas',
  JsonFlow.ValidationRules.Enum in '..\Source\Schema\Validators\JsonFlow.ValidationRules.Enum.pas',
  JsonFlow.ValidationRules.ExclusiveMaximum in '..\Source\Schema\Validators\JsonFlow.ValidationRules.ExclusiveMaximum.pas',
  JsonFlow.ValidationRules.ExclusiveMinimum in '..\Source\Schema\Validators\JsonFlow.ValidationRules.ExclusiveMinimum.pas',
  JsonFlow.ValidationRules.Format in '..\Source\Schema\Validators\JsonFlow.ValidationRules.Format.pas',
  JsonFlow.ValidationRules.Items in '..\Source\Schema\Validators\JsonFlow.ValidationRules.Items.pas',
  JsonFlow.ValidationRules.Maximum in '..\Source\Schema\Validators\JsonFlow.ValidationRules.Maximum.pas',
  JsonFlow.ValidationRules.MaxItems in '..\Source\Schema\Validators\JsonFlow.ValidationRules.MaxItems.pas',
  JsonFlow.ValidationRules.MaxLength in '..\Source\Schema\Validators\JsonFlow.ValidationRules.MaxLength.pas',
  JsonFlow.ValidationRules.MaxProperties in '..\Source\Schema\Validators\JsonFlow.ValidationRules.MaxProperties.pas',
  JsonFlow.ValidationRules.Minimum in '..\Source\Schema\Validators\JsonFlow.ValidationRules.Minimum.pas',
  JsonFlow.ValidationRules.MinItems in '..\Source\Schema\Validators\JsonFlow.ValidationRules.MinItems.pas',
  JsonFlow.ValidationRules.MinLength in '..\Source\Schema\Validators\JsonFlow.ValidationRules.MinLength.pas',
  JsonFlow.ValidationRules.MinProperties in '..\Source\Schema\Validators\JsonFlow.ValidationRules.MinProperties.pas',
  JsonFlow.ValidationRules.MultipleOf in '..\Source\Schema\Validators\JsonFlow.ValidationRules.MultipleOf.pas',
  JsonFlow.ValidationRules.NotRule in '..\Source\Schema\Validators\JsonFlow.ValidationRules.NotRule.pas',
  JsonFlow.ValidationRules.OneOf in '..\Source\Schema\Validators\JsonFlow.ValidationRules.OneOf.pas',
  JsonFlow.ValidationRules.Pattern in '..\Source\Schema\Validators\JsonFlow.ValidationRules.Pattern.pas',
  JsonFlow.ValidationRules.PatternProperties in '..\Source\Schema\Validators\JsonFlow.ValidationRules.PatternProperties.pas',
  JsonFlow.ValidationRules.Properties in '..\Source\Schema\Validators\JsonFlow.ValidationRules.Properties.pas',
  JsonFlow.ValidationRules.PropertyNames in '..\Source\Schema\Validators\JsonFlow.ValidationRules.PropertyNames.pas',
  JsonFlow.ValidationRules.Required in '..\Source\Schema\Validators\JsonFlow.ValidationRules.Required.pas',
  JsonFlow.ValidationRules.Types in '..\Source\Schema\Validators\JsonFlow.ValidationRules.Types.pas',
  JsonFlow.ValidationRules.UniqueItems in '..\Source\Schema\Validators\JsonFlow.ValidationRules.UniqueItems.pas';

begin
  try
    { TODO -oUser -cConsole Main : Insert code here }
  except
    on E: Exception do
      Writeln(E.ClassName, ': ', E.Message);
  end;
end.
